name = "Cobble S3"
author = "AmeMeida"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99fefea3654303f6fae6ca6738f3366c04c20413ca8b148301edb5379dec08c0"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
