name = "Cobble S3"
author = "AmeMeida"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91e35ad033d78e7d9e8bdea8fe381d128386c9f79583cbea8c4f1961ed1faa3e"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
