name = "Cobble S3"
author = "AmeMeida"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "710cc5080b1612c8734cc6fb342a7f18facd66627b795eda561871cbd9ec0d31"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
