name = "Cobble S3"
author = "AmeMeida"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cadf708ef7644813a8ca4c11588cc890a04a8a4be5539314208b5d595330048b"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
