name = "Cobble S3"
author = "AmeMeida"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f0e314f514f37894cc9c48de41edace3384be3dca07115b32b3f69d4ed953df"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
