name = "Cobble S3"
author = "AmeMeida"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74345c0547e5210ae683bc1de2c6e2dcc5489580247c2c5db1536e446fc36bf3"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
